[toolchain]
anchor_version = "0.29.0"
solana_version = "2.0.24"

[features]
seeds = false
skip-lint = false

[programs.devnet]
irm-base = "HqfsZmdbtUiG5cv2HDhB4c7Ewjoxqe2NnEWzA9HJyCEQ"
lego_lend = "AQiKvjW1VD1ndzhKKTAzcVzqyoNCpotseY9Pt4iQUZgG"
oracle-base = "L6eUquiyrvQfbdKVn76qMiH8ZgbJFBFAjY1fjoapDEg"

[programs.localnet]
irm-base = "HqfsZmdbtUiG5cv2HDhB4c7Ewjoxqe2NnEWzA9HJyCEQ"
lego_lend = "AQiKvjW1VD1ndzhKKTAzcVzqyoNCpotseY9Pt4iQUZgG"
oracle-base = "L6eUquiyrvQfbdKVn76qMiH8ZgbJFBFAjY1fjoapDEg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sahil/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/legoLend/admin/createMarket.test.ts"

test_irm_base_initialize = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/irmBase/initialize.test.ts"
test_irm_base_update = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/irmBase/update.test.ts"

test_lego_lend_initialize = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/legoLend/initialize.test.ts"
test_lego_lend_set_fee_recipient = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/legoLend/admin/setFeeRecipient.test.ts"
test_lego_lend_transfer_ownership = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/legoLend/admin/transferOwnership.test.ts"
test_lego_lend_create_market = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/legoLend/admin/createMarket.test.ts"
test_lego_lend_accrue_interest = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/legoLend/accrueInterest.test.ts"

test_oracle_base_initialize = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/oracleBase/initialize.test.ts"
test_oracle_base_update = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/oracleBase/update.test.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
