[toolchain]
anchor_version = "0.29.0"
solana_version = "2.0.24"

[features]
seeds = false
skip-lint = false

[programs.devnet]
lego_lend = "AQiKvjW1VD1ndzhKKTAzcVzqyoNCpotseY9Pt4iQUZgG"

[programs.localnet]
lego_lend = "AQiKvjW1VD1ndzhKKTAzcVzqyoNCpotseY9Pt4iQUZgG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sahil/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
